# Generated by Django 3.1.2 on 2020-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('money_raised', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('img_name', models.CharField(default=None, max_length=50, null=True)),
                ('body', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
